// src/components/mobile-menu/MobileMenu.tsx
'use client';

import React from 'react';
import { useMainStore } from '@/store/useMainStore';
import { Navigation } from '@/components/navigation/Navigation';

interface MobileMenuProps extends React.HTMLAttributes<HTMLDivElement> {
  items?: any[];
  dark?: boolean;
}

export const MobileMenu: React.FC<MobileMenuProps> = ({
  items = [],
  dark = false,
  className,
  ...props
}) => {
  const isMobileActive = useMainStore(state => state.isMobileActive);
  const setIsMobileActive = useMainStore(state => state.setIsMobileActive);

  const onClick = () => {
    setIsMobileActive(!isMobileActive);
  };

  return (
    <div className={className} {...props}>
      <div className="block relative z-[1] select-none">
        <input
          type="checkbox"
          onClick={onClick}
          className="block w-10 h-8 absolute top-[-7px] left-[-5px] cursor-pointer opacity-0 z-[2]"
        />

        <span className={`block w-[33px] h-1 mb-[5px] relative bg-[#212529] rounded-[3px] z-[1] origin-[4px_0px] transition-all duration-500 ease-[cubic-bezier(0.77,0.2,0.05,1)] first:origin-[0%_0%] [&:nth-last-child(2)]:origin-[0%_100%] ${
          isMobileActive ? 'opacity-100 rotate-45 -translate-x-0.5 -translate-y-px' : ''
        }`}></span>
        <span className={`block w-[33px] h-1 mb-[5px] relative bg-[#212529] rounded-[3px] z-[1] origin-[4px_0px] transition-all duration-500 ease-[cubic-bezier(0.77,0.2,0.05,1)] first:origin-[0%_0%] [&:nth-last-child(2)]:origin-[0%_100%] ${
          isMobileActive ? 'opacity-0 scale-[0.2]' : ''
        }`}></span>
        <span className={`block w-[33px] h-1 mb-[5px] relative bg-[#212529] rounded-[3px] z-[1] origin-[4px_0px] transition-all duration-500 ease-[cubic-bezier(0.77,0.2,0.05,1)] first:origin-[0%_0%] [&:nth-last-child(2)]:origin-[0%_100%] ${
          isMobileActive ? 'opacity-100 -rotate-45 translate-x-0 -translate-y-px' : ''
        }`}></span>

        <Navigation
          className={`${isMobileActive ? 'flex' : 'hidden'} fixed top-0 bottom-0 right-0 left-0 w-full flex-col justify-center [&>*]:text-center [&>*]:py-2.5 [&>*]:px-0 [&>*]:w-full -mt-[200px] bg-[#f0f0f8]`}
          items={items}
          onClicked={() => setIsMobileActive(false)}
        />
      </div>
    </div>
  );
};

// src/components/mobileMenu/mobileMenu.vue
<template>
  <div class="mobile-menu">
    <div
      class="mobile-menu__toggle"
      :class="{ 'mobile-menu__toggle--active': isMobileActive }"
    >
      <input type="checkbox" @click="onClick" />

      <span></span>
      <span></span>
      <span></span>

      <Navigation
        class="mobile-menu__navigation"
        :items="items"
        @clicked="$accessor.setIsMobileActive(false)"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from '@vue/composition-api'
import Navigation from '~/components/navigation/navigation.vue'
export default defineComponent({
  components: { Navigation },
  props: {
    items: {
      type: Array,
      default: () => [] as any[]
    },
    dark: Boolean
  },

  setup(_props, { root }) {
    const isMobileActive = computed(() => root.$accessor.isMobileActive)
    const onClick = () => {
      root.$accessor.setIsMobileActive(!isMobileActive.value)
    }
    return { onClick, isMobileActive }
  }
})
</script>

TODO: Add browser prefixes
<style lang="scss">
.mobile-menu {
  &__toggle {
    display: block;
    position: relative;

    z-index: 1;

    -webkit-user-select: none;
    user-select: none;

    input {
      display: block;
      width: 40px;
      height: 32px;
      position: absolute;
      top: -7px;
      left: -5px;

      cursor: pointer;

      opacity: 0;
      z-index: 2;

      -webkit-touch-callout: none;
    }

    &--active {
      span {
        opacity: 1;
        transform: rotate(45deg) translate(-2px, -1px);
        background: $secondary-color-100;

        &:nth-last-child(3) {
          opacity: 0;
          transform: rotate(0deg) scale(0.2, 0.2);
        }

        &:nth-last-child(2) {
          transform: rotate(-45deg) translate(0, -1px);
        }
      }

      .mobile-menu__navigation {
        display: flex;
      }
    }

    span {
      display: block;
      width: 33px;
      height: 4px;
      margin-bottom: 5px;
      position: relative;

      background: $secondary-color-100;
      border-radius: 3px;

      z-index: 1;

      transform-origin: 4px 0px;

      transition: transform 0.5s cubic-bezier(0.77, 0.2, 0.05, 1),
        background 0.5s cubic-bezier(0.77, 0.2, 0.05, 1), opacity 0.55s ease;

      &:first-child {
        transform-origin: 0% 0%;
      }

      &:nth-last-child(2) {
        transform-origin: 0% 100%;
      }
    }
  }

  &__navigation {
    display: none;
    position: fixed;
    top: 0;
    bottom: 0;
    right: 0;
    left: 0;
    width: 100%;

    flex-flow: column;
    justify-content: center;
    & .navigation__item {
      text-align: center;
      padding: 10px 0;
      width: 100%;
    }

    margin-top: -200px;

    background: $color-0;
  }
}
</style>
