// src/components/navigation/navigationItem.vue
<template>
  <div class="navigation-item">
    <el-button
      v-if="isButton"
      class="navigation-item__button"
      type="primary"
      @click="go(to)"
      >{{ name }}</el-button
    >
    <a
      v-if="
        !isButton && to && (to.includes('https://') || to.includes('mailto'))
      "
      class="navigation-item__link"
      :class="{'navigation-item__link--dark': dark}"
      :href="to"
      target="_blank"
      rel="nofollow noopener noreferrer"
      >{{ name }}</a
    >
    <nuxt-link
      v-if="
        !isButton && to && !to.includes('https://') && !to.includes('mailto')
      "
      class="navigation-item__link"
      rel="nofollow noopener noreferrer"
      :class="{'navigation-item__link--dark': dark}"
      :to="{name: to}"
    >
      {{ name }}
    </nuxt-link>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@vue/composition-api'
import NavigationItem from '~/components/navigation/navigationItem.vue'
export default defineComponent({
  components: {NavigationItem},
  props: {
    to: {
      type: String,
    },
    name: {
      type: String,
    },
    isButton: Boolean,
    dark: Boolean,
  },
  methods: {
    go(to) {
      window.open(to, '_blank')
    },
  },
})
</script>

<style lang="scss">
.navigation-item {
  &__link {
    transition: all ease-in 0.1s;

    &--dark {
      color: white;
    }
    &:hover,
    &.nuxt-link-active {
      color: $primary-color-100;
    }
  }

  &__button {
    min-width: 100px;
  }
}
</style>

// apps/web/src/components/navigation/NavigationItem.tsx
'use client';

import React from 'react';
import { Link, usePathname } from '@/i18n/routing';
import { Button } from '@/components/ui/button';

interface NavigationItemProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onClick'> {
  to?: string;
  name?: string;
  isButton?: boolean;
  dark?: boolean;
  onClick?: () => void;
}

export const NavigationItem: React.FC<NavigationItemProps> = ({
  to,
  name,
  isButton = false,
  dark = false,
  className,
  onClick,
  ...props
}) => {
  const pathname = usePathname();

  const go = (url: string) => {
    window.open(url, '_blank');
  };

  const isActive = to && (pathname.endsWith(`/${to}`) || pathname.includes(`/${to}/`));

  const handleClick = () => {
    if (onClick) onClick();
  };

  // WhyHive button
  if (isButton && to && to.includes('whyhive.co')) {
    return (
      <div className={`py-[5px] px-[5px] ${className || ''}`} {...props}>
        <Button
          variant="outline"
          onClick={() => {
            go(to);
            handleClick();
          }}
        >
          {name}
        </Button>
      </div>
    );
  }

  // Regular button
  if (isButton && to && !to.includes('whyhive.co')) {
    return (
      <div className={`py-[5px] px-[5px] ${className || ''}`} {...props}>
        <Button
          className="min-w-[90px]"
          onClick={() => {
            go(to);
            handleClick();
          }}
        >
          {name}
        </Button>
      </div>
    );
  }

  // External link
  if (!isButton && to && (to.includes('https://') || to.includes('mailto'))) {
    return (
      <div className={`py-[5px] px-[5px] ${className || ''}`} {...props}>
        <a
          className={`transition-all ease-in duration-100 hover:text-[#e31337] ${dark ? 'text-white' : ''}`}
          href={to}
          target="_blank"
          rel="nofollow noopener noreferrer"
          onClick={handleClick}
        >
          {name}
        </a>
      </div>
    );
  }

  // Internal link
  if (!isButton && to && !to.includes('https://') && !to.includes('mailto')) {
    return (
      <div className={`py-[5px] px-[5px] ${className || ''}`} {...props}>
        <Link
          href={`/${to}` as any}
          className={`transition-all ease-in duration-100 hover:text-[#e31337] ${dark ? 'text-white' : ''} ${isActive ? 'text-[#e31337]' : ''}`}
          onClick={handleClick}
        >
          {name}
        </Link>
      </div>
    );
  }

  return null;
};
