// src/components/statWebsite/statWebsite.vue
<template>
  <div class="statWebsite" :class="`statWebsite--${item.id}`">
    <a
      :href="item.website"
      target="_blank"
      rel="nofollow noopener noreferrer"
      class="statWebsite__inner"
      :class="{
        'statWebsite__inner--hover': hover,
        'statWebsite__inner--transparent': transparent,
      }"
      @mouseenter="hover = true"
      @mouseleave="hover = false"
    >
      <div class="statWebsite__image">
        <img :src="getImage(item.image)" />
      </div>
    </a>

    <a
      :href="item.website"
      target="_blank"
      rel="nofollow noopener noreferrer"
      class="statWebsite__name"
      :class="{'statWebsite__name--hover': hover}"
      @mouseenter="hover = true"
      @mouseleave="hover = false"
      >{{ item.name
      }}<fa-icon
        class="statWebsite__name__icon"
        :icon="['fas', 'external-link-alt']"
      ></fa-icon
    ></a>

    <a
      v-if="item.github || item.gitlab"
      :href="item.github || item.gitlab"
      target="_blank"
      rel="nofollow noopener noreferrer"
      class="statWebsite__git"
      >{{ item.github ? 'Github' : 'Gitlab'
      }}<fa-icon
        class="statWebsite__git__icon"
        :icon="['fas', 'external-link-alt']"
      ></fa-icon
    ></a>
  </div>
</template>

<script lang="ts">
import {defineComponent, ref} from '@nuxtjs/composition-api'

export default defineComponent({
  props: {
    item: {
      type: Object,
      default: () => {},
    },
    transparent: Boolean,
  },

  setup(_props) {
    const hover = ref(false)
    const getImage = (image) => {
      try {
        return require(`~/assets/images/websites/${image}`)
      } catch (error) {
        return ''
      }
    }
    return {getImage, hover}
  },
})
</script>

<style lang="scss">
.statWebsite {
  display: flex;
  flex-flow: column;
  align-items: center;
  justify-content: center;
  margin: 25px 40px;

  &__inner {
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 10px;
    background: #e2e2ec;
    height: 60px;
    width: 250px;
    padding: 12px;
    margin-bottom: 8px;
    transition: transform 0.5s;
    box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.03);
    &:hover,
    &--hover {
      transform: translateY(-10%);
    }

    &--transparent {
      background: transparent;
      box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);
    }
  }

  &__icons {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 2px;
  }

  &__icon {
    margin: 4px;
  }

  &__name {
    display: flex;
    align-items: center;
    margin-top: 2px;
    margin-bottom: 6px;
    font-size: 1.25rem;
    transition: all ease-in 0.1s;
    &:hover,
    &--hover {
      color: $primary-color-100;
    }

    &__icon {
      height: 8px;
      margin-left: 5px;
    }
  }

  &__git {
    display: flex;
    align-items: center;
    margin-top: 4px;
    font-size: 0.88rem;
    transition: all ease-in 0.1s;
    &:hover {
      color: $primary-color-100;
    }

    &__icon {
      height: 7px;
      margin-left: 5px;
    }
  }

  &__image {
    display: flex;
    justify-self: center;
    height: 100%;
    width: 100%;
    max-height: 40px;
    img {
      height: 100%;
      width: 100%;
      object-fit: contain;
    }
  }

  &--dapp-review,
  &--stateofthedapps {
    .statWebsite__inner {
      background: #2e3135;
    }
  }

  &--dapp-com,
  &--hivedapps-com {
    .statWebsite__inner {
      background: white;
    }
  }
}

@media (max-width: 525px) {
  .statWebsite {
    margin: 20px 20px 40px 20px;
  }
}

@media (max-width: 425px) {
  .statWebsite {
    margin: 15px 15px 30px 15px;
  }
}
</style>

// apps/web/src/components/statWebsite/StatWebsite.tsx
'use client';

import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faExternalLinkAlt } from '@fortawesome/free-solid-svg-icons';
import { useAssets } from '@/hooks/useAssets';

interface StatWebsiteProps {
  item?: any;
  transparent?: boolean;
}

export const StatWebsite: React.FC<StatWebsiteProps> = ({
  item = {},
  transparent = false
}) => {
  const { getImage: getAssetImage } = useAssets();
  const [hover, setHover] = useState(false);

  const getImage = (image: string) => {
    return getAssetImage(`websites/${image}`);
  };

  const isDarkBackground = item.id === 'dapp-review' || item.id === 'stateofthedapps';
  const isWhiteBackground = item.id === 'dapp-com' || item.id === 'hivedapps-com';

  return (
    <div className="flex flex-col items-center justify-center mx-10 my-[25px] max-[525px]:mx-5 max-[525px]:my-5 max-[525px]:mb-10 max-[425px]:mx-[15px] max-[425px]:my-[15px] max-[425px]:mb-[30px]">
      <a
        href={item.website}
        target="_blank"
        rel="nofollow noopener noreferrer"
        className={`flex justify-center items-center rounded-[10px] h-[60px] w-[250px] p-3 mb-2 transition-transform duration-500 shadow-[0px_0px_15px_rgba(0,0,0,0.03)] hover:-translate-y-[10%] ${
          hover ? '-translate-y-[10%]' : ''
        } ${
          transparent
            ? 'bg-transparent shadow-[0px_0px_15px_rgba(0,0,0,0.2)]'
            : isDarkBackground
            ? 'bg-[#2e3135]'
            : isWhiteBackground
            ? 'bg-white'
            : 'bg-[#e2e2ec]'
        }`}
        onMouseEnter={() => setHover(true)}
        onMouseLeave={() => setHover(false)}
      >
        <div className="flex justify-self-center h-full w-full max-h-[40px]">
          <img src={getImage(item.image)} alt={item.name} className="h-full w-full object-contain" />
        </div>
      </a>

      <a
        href={item.website}
        target="_blank"
        rel="nofollow noopener noreferrer"
        className={`flex items-center mt-0.5 mb-1.5 text-xl transition-all ease-in duration-100 hover:text-[#e31337] ${
          hover ? 'text-[#e31337]' : ''
        }`}
        onMouseEnter={() => setHover(true)}
        onMouseLeave={() => setHover(false)}
      >
        {item.name}
        <FontAwesomeIcon
          className="h-2 ml-[5px]"
          icon={faExternalLinkAlt}
        />
      </a>

      {(item.github || item.gitlab) && (
        <a
          href={item.github || item.gitlab}
          target="_blank"
          rel="nofollow noopener noreferrer"
          className="flex items-center mt-1 text-[0.88rem] transition-all ease-in duration-100 hover:text-[#e31337]"
        >
          {item.github ? 'Github' : 'Gitlab'}
          <FontAwesomeIcon
            className="h-[7px] ml-[5px]"
            icon={faExternalLinkAlt}
          />
        </a>
      )}
    </div>
  );
};
