// src/components/contributors/contributorsContributor.vue
<template>
  <div class="contributors-contributor">
    <img
      class="contributors-contributor__image"
      :src="
        contributor.image
          ? getImage(contributor.image)
          : `https://images.hive.blog/u/${contributor.social.hive}/avatar/large`
      "
    />
    <a
      class="contributors-contributor__name"
      :href="`${links.hive}${contributor.social.hive}`"
      target="_blank"
      rel="nofollow noopener noreferrer"
      >{{ contributor.name }}</a
    >
    <div class="contributors-contributor__label">
      {{ contributor.labels.join(' & ').replace('Core Developer', 'Core Dev') }}
    </div>
    <div class="contributors-contributor__socials">
      <a
        v-for="social in Object.entries(contributor.social)"
        :key="social[0]"
        :href="`${links[social[0]]}${social[1]}`"
        target="_blank"
        rel="nofollow noopener noreferrer"
      >
        <fa-icon
          class="contributors-contributor__icon"
          :icon="['fab', social[0]]"
        />
      </a>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@nuxtjs/composition-api'
import {IContributor} from '~/types/index'

export default defineComponent({
  props: {
    contributor: {
      type: Object,
      default: {} as IContributor,
    },
  },

  setup() {
    const getImage = (image) => {
      try {
        return require(`~/assets/images/contributors/${image}`)
      } catch (error) {
        return ''
      }
    }

    const links = {
      linkedin: 'https://www.linkedin.com/in/',
      hive: 'https://hive.blog/@',
      twitter: 'https://twitter.com/',
    }
    return {getImage, links}
  },
})
</script>

<style lang="scss">
.contributors-contributor {
  display: flex;
  flex-flow: column nowrap;
  padding: 14px;
  background: #e2e2ec;
  border-radius: 5px;
  &__image {
    min-height: 190px;
    min-width: 190px;
    max-height: 190px;
    max-width: 190px;
    height: 100%;
    width: 100%;
    object-fit: contain;
    border-radius: 10px;
  }

  &__name {
    font-size: 1.2rem;
    font-weight: 700;
    padding: 6px 10px;
    margin: 10px 4px 10px 4px;
    background: #f0f0f7;
    color: #555555;
    border-radius: 14px 14px 1px 1px;
    text-align: center;
    cursor: pointer;
  }

  &__labels {
    display: flex;
  }

  &__label {
    font-size: 0.8rem;
    color: #787885;
    text-align: center;
  }

  &__socials {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 5px;
  }

  &__icon {
    height: 20px;
    width: 20px;
    cursor: pointer;
    margin: 5px 6px;
    opacity: 1;
    color: #787885;
  }
}

@media (max-width: 768px) {
  .contributors-contributor {
    &__image {
      max-height: 160px;
      max-width: 160px;
    }
  }
}

@media (max-width: 720px) {
  .contributors-contributor {
    flex: 1;
    &__image {
      max-height: 100%;
      max-width: 100%;
      min-width: 150px;
      min-height: 150px;
    }
  }
}
</style>

// apps/web/src/components/contributors/ContributorsContributor.tsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { useAssets } from '@/hooks/useAssets';
import type { IContributor } from '@/types';

interface ContributorsContributorProps {
  contributor?: IContributor;
  className?: string;
}

const links: Record<string, string> = {
  linkedin: 'https://www.linkedin.com/in/',
  hive: 'https://hive.blog/@',
  twitter: 'https://twitter.com/',
};

export const ContributorsContributor: React.FC<ContributorsContributorProps> = ({
  contributor = {} as IContributor,
  className = ''
}) => {
  const { getImage: getAssetImage } = useAssets();

  const getImage = (image: string) => {
    return getAssetImage(`contributors/${image}`);
  };

  const imageUrl = contributor.image
    ? getImage(contributor.image)
    : `https://images.hive.blog/u/${contributor.social?.hive}/avatar/large`;

  return (
    <div className={`group flex flex-col items-center p-2.5 bg-[#e2e2ec] rounded-lg w-[115px] max-[600px]:w-[95px] ${className}`}>
      <a
        href={`${links.hive}${contributor.social?.hive}`}
        target="_blank"
        rel="nofollow noopener noreferrer"
        className="block"
      >
        <img
          className="h-[85px] w-[85px] max-[600px]:h-[70px] max-[600px]:w-[70px] object-cover rounded-full"
          src={imageUrl}
          alt={contributor.name}
        />
      </a>
      <a
        className="mt-2 text-[0.8rem] max-[600px]:text-[0.7rem] font-semibold text-[#555] text-center leading-tight hover:text-[#e31337] transition-colors truncate w-full"
        href={`${links.hive}${contributor.social?.hive}`}
        target="_blank"
        rel="nofollow noopener noreferrer"
      >
        {contributor.name}
      </a>
      <div className="mt-0.5 text-[0.65rem] max-[600px]:text-[0.55rem] text-[#787885] text-center leading-tight line-clamp-2 min-h-[2lh]">
        {contributor.labels?.join(' & ').replace('Core Developer', 'Core Dev')}
      </div>
      <div className="flex items-center justify-center mt-1.5 gap-1">
        {contributor.social && Object.entries(contributor.social).map(([platform, handle]) => (
          <a
            key={platform}
            href={`${links[platform]}${handle}`}
            target="_blank"
            rel="nofollow noopener noreferrer"
            className="text-[#787885] hover:text-[#e31337] transition-colors"
          >
            <FontAwesomeIcon
              className="h-3.5 w-3.5"
              icon={['fab', platform] as any}
            />
          </a>
        ))}
      </div>
    </div>
  );
};
