// apps/web/src/components/contributors/Contributors.tsx
'use client';

import React, { useEffect, useMemo } from 'react';
import { useSearchParams } from 'next/navigation';
import { useRouter } from '@/i18n/routing';
import { useMainStore } from '@/store/useMainStore';
import { CONTRIBUTORS, CONTRIBUTOR_LABELS } from '@/lib/data/var';
import type { IContributor } from '@/types';
import { ContributorLabel } from './ContributorLabel';
import { ContributorsContributor } from './ContributorsContributor';

interface ContributorsProps {
  full?: boolean;
}

export const Contributors: React.FC<ContributorsProps> = ({ full = true }) => {
  const searchParams = useSearchParams();
  const router = useRouter();

  const shuffledContributors = useMainStore(state => state.shuffledContributors);
  const contributors = useMainStore(state => state.contributors);
  const setContributors = useMainStore(state => state.setContributors);
  const shuffleContributors = useMainStore(state => state.shuffleContributors);

  const filterParam = searchParams.get('t');

  const contributorLabels = useMemo(() => {
    return Object.keys(CONTRIBUTOR_LABELS)
      .filter((l: string) => {
        return shuffledContributors.find(
          (c: IContributor) => !c.inactive && c.labels.includes(l as any)
        );
      })
      .map((l: string) => {
        return {
          value: l,
          count: shuffledContributors.filter(
            (c: IContributor) => !c.inactive && c.labels.includes(l as any)
          ).length,
        };
      });
  }, [shuffledContributors]);

  const getFilteredContributors = (key: string | null | undefined) => {
    setContributors(
      shuffledContributors.filter(
        (e: IContributor) => !e.inactive && (!key || e.labels.includes(key as any))
      )
    );
  };

  useEffect(() => {
    if (contributors.length <= 0) {
      getFilteredContributors(filterParam);
    }
  }, []);

  useEffect(() => {
    getFilteredContributors(filterParam);
  }, [filterParam, shuffledContributors]);

  const filterLabel = (key: string) => {
    if (filterParam === key) {
      router.push('/contributors');
    } else {
      router.push(`/contributors?t=${key}`);
    }
  };

  return (
    <div className="flex flex-col flex-nowrap items-center w-full min-h-[500px]">
      {/* Hero Section */}
      <div className="flex flex-col items-center text-center mb-16">
        <h1 className="text-[4rem] font-bold leading-tight mb-6 max-[600px]:text-[3rem]">
          Our Builders<span className="text-[#e31337]">.</span>
        </h1>
        <p className="text-xl max-w-[700px] text-[#555] leading-relaxed mb-4">
          We're a decentralized project, running on more than{' '}
          {CONTRIBUTORS.length} people contributing regularly to the Hive
          Ecosystem.
        </p>
        <p className="text-lg text-[#555]">
          The list of contributors below is{' '}
          <span className="text-[#e31337] cursor-pointer hover:underline font-medium" onClick={() => shuffleContributors()}>
            randomized
          </span>
          .
        </p>
      </div>

      {/* Filter Labels */}
      <div className="flex flex-row flex-wrap justify-center gap-3 mb-12">
        {contributorLabels.map((label) => (
          <ContributorLabel
            key={label.value}
            className={
              filterParam && filterParam !== label.value
                ? 'opacity-40 hover:opacity-75'
                : ''
            }
            label={label.value}
            count={label.count}
            onClick={() => filterLabel(label.value)}
          />
        ))}
      </div>

      {/* Contributors Grid */}
      <div className="flex flex-row flex-wrap justify-center w-full gap-3 max-[600px]:gap-2">
        {contributors.map((contributor) => (
          <ContributorsContributor
            key={contributor.id}
            contributor={contributor}
          />
        ))}
      </div>
    </div>
  );
};

// src/components/contributors/contributors.vue
<template>
  <div class="contributors">
    <h1>Built by the community</h1>
    <div class="contributors__subtitle">
      We're a decentralized project, running on more than
      {{ CONTRIBUTORS.length }} people contributing regularly to the Hive
      Ecosystem.
    </div>
    <div>
      The list of contributors below is
      <i class="link" @click="$accessor.shuffleContributors({})">randomized</i>.
    </div>

    <div class="contributors__labels">
      <ContributorsContributorLabel
        v-for="label in contributorLabels"
        :key="label.value"
        :class="{
          'contributors__label--inactive':
            $route.query.t && $route.query.t !== label.value,
        }"
        :label="label.value"
        :count="label.count"
        @click.native="filterLabel(label.value)"
      />
    </div>
    <div class="contributors__container">
      <ContributorsContributor
        v-for="contributor in $accessor.contributors"
        :key="contributor.id"
        class="contributors__contributor"
        :contributor="contributor"
      />
    </div>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  useAsync,
  computed,
  ref,
  watch,
  useRoute,
} from '@nuxtjs/composition-api'
import {shuffleArray, routerPush} from '~/helpers/util'
import {CONTRIBUTORS, CONTRIBUTOR_LABELS} from '~/helpers/var'
import {IContributor} from '~/types'

export default defineComponent({
  props: {
    full: {
      type: Boolean,
      default: true,
    },
  },

  setup(_props, {root}) {
    const route = useRoute()

    const contributorLabels = computed(() =>
      Object.keys(CONTRIBUTOR_LABELS)
        .filter((l) => {
          return root.$accessor.shuffledContributors.filter(
            (c) => !c.inactive && c.labels.includes(l as any),
          )[0]
        })
        .map((l) => {
          return {
            value: l,
            count: root.$accessor.shuffledContributors.filter(
              (c) => !c.inactive && c.labels.includes(l as any),
            ).length,
          }
        }),
    )

    const filteredContributors = ref([] as any)

    const getFilteredContributors = (key) => {
      root.$accessor.setContributors(
        root.$accessor.shuffledContributors.filter(
          (e) => !e.inactive && (!key || e.labels.includes(key)),
        ),
      )
    }

    useAsync(() => {
      if (root.$accessor.contributors.length <= 0)
        getFilteredContributors(route.value.query.t)
    })
    watch(
      () => route.value.query.t,
      (newT) => getFilteredContributors(newT),
    )
    watch(
      () => root.$accessor.shuffledContributors,
      () => getFilteredContributors(route.value.query.t),
    )

    return {
      filteredContributors: filteredContributors as IContributor[],
      contributorLabels,
      CONTRIBUTORS,
    }
  },
  methods: {
    async filterLabel(key: string) {
      if (this.$route.query.t === key) {
        await routerPush(this, `/contributors`)
      } else {
        await routerPush(this, `/contributors?t=${key}`)
      }
    },
  },
})
</script>

<style lang="scss">
.contributors {
  display: flex;
  flex-flow: column nowrap;
  align-items: center;
  max-width: 1200px;
  width: 100%;
  min-height: 500px;

  &__subtitle {
    margin-bottom: 10px;
  }

  &__labels {
    display: flex;
    flex-flow: row wrap;
    margin-top: 20px;
    margin-bottom: 15px;
    .contributor-label {
      margin-right: 12px;
      margin-bottom: 8px;
    }
  }

  &__label {
    &--inactive {
      opacity: 0.333;
      &:hover {
        opacity: 0.75;
      }
    }
  }

  &__container {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
    width: 100%;
  }

  &__contributor {
    margin: 10px;
  }
}
</style>
