// src/components/contributors/contributorLabel.vue
<template>
  <div
    class="contributor-label"
    :class="{'contributor-label--withCount': Boolean(count)}"
    :style="`background: ${CONTRIBUTOR_LABELS[label].background}; color:  ${CONTRIBUTOR_LABELS[label].text}`"
  >
    {{ label }}
    <span v-if="count">({{ count }})</span>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@nuxtjs/composition-api'
import {CONTRIBUTOR_LABELS} from '~/helpers/var'
export default defineComponent({
  props: {
    label: {
      type: String,
      default: '',
    },
    count: Number,
  },

  setup() {
    return {CONTRIBUTOR_LABELS}
  },
})
</script>

<style lang="scss">
.contributor-label {
  padding: 5px;
  border-radius: 6px;
  text-transform: uppercase;
  font-size: 0.7rem;
  font-weight: 600;
  cursor: pointer;

  &--withCount {
    font-size: 1.1rem;
    padding: 7px 15px;
  }
}

@media (max-width: 768px) {
  .contributor-label {
    width: calc(50% - 42px);
    &--withCount {
      font-size: 0.8rem;
    }
  }
}
</style>

// src/components/contributors/ContributorLabel.tsx
import React from 'react';
import { CONTRIBUTOR_LABELS } from '@/lib/data/var';

interface ContributorLabelProps {
  label?: string;
  count?: number;
  className?: string;
  onClick?: () => void;
}

export const ContributorLabel: React.FC<ContributorLabelProps> = ({
  label = '',
  count,
  className = '',
  onClick
}) => {
  const colors = CONTRIBUTOR_LABELS[label as keyof typeof CONTRIBUTOR_LABELS] || {
    background: 'transparent',
    text: 'inherit'
  };

  return (
    <div
      className={`p-[5px] rounded-md uppercase text-[0.7rem] font-semibold cursor-pointer ${
        count ? 'text-base py-[7px] px-[15px] max-[768px]:text-[0.8rem]' : ''
      } max-[768px]:w-[calc(50%-42px)] ${className}`}
      style={{
        background: colors.background,
        color: colors.text
      }}
      onClick={onClick}
    >
      {label}
      {count && <span>({count})</span>}
    </div>
  );
};
