// src/components/infobar/infobar.vue
<template>
  <div
    v-if="
      state.setInterval && (!isReady || (isReady && !infobar.hideWhenReady))
    "
    class="infobar"
    :class="{'infobar--active': isReady}"
  >
    <div v-if="!isReady" class="infobar__countdown">
      <div class="infobar__countdown__textWrapper">
        <span
          v-if="infobar.titleDesktopOnly"
          class="infobar__countdown__preText--desktopOnly"
          >{{ infobar.titleDesktopOnly }}</span
        >
        <span class="infobar__countdown__preText">{{ infobar.title }}</span>
      </div>
      <div class="infobar__countdown__timeBox" @click="go()">
        <span class="infobar__countdown__time">{{ formattedCountdown }}</span>
      </div>
    </div>
    <div v-if="state.setInterval && isReady" class="infobar__ready" @click="go()">
      {{ infobar.titleReady }}
    </div>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  reactive,
  onBeforeUnmount,
  computed,
  ref,
  onMounted,
} from '@nuxtjs/composition-api'
import moment from 'moment'
import {INFOBAR} from '../../helpers/var'

export default defineComponent({
  props: {},

  setup() {
    const state = reactive({
      d: '0',
      h: '0',
      m: '0',
      s: '00',
      interval: null as any,
      setInterval: false,
    })

    const infobar = ref(INFOBAR)

    const setCountdown = () => {
      const then = moment.utc(INFOBAR.date).valueOf()
      const now = moment.utc().valueOf()
      if (then - now < 0) {
        clearInterval(state.interval)
        state.d = '0'
        state.h = '0'
        state.m = '0'
        state.s = '0'
        return
      }
      const countdown = moment(then - now)
      const dNum = Number(countdown.utc().format('DD')) - 1
      const hNum = Number(countdown.utc().format('HH'))
      const mNum = Number(countdown.utc().format('mm'))
      const sNum = Number(countdown.utc().format('ss'))

      // Only show leading zeros when needed
      state.d = String(dNum)
      state.h = dNum > 0 ? (hNum < 10 ? '0' : '') + String(hNum) : String(hNum)
      state.m = (dNum > 0 || hNum > 0) ? (mNum < 10 ? '0' : '') + String(mNum) : String(mNum)
      state.s = (sNum < 10 ? '0' : '') + String(sNum)
    }

    onMounted(() => {
      setCountdown()
      state.interval = setInterval(() => {
        state.setInterval = true
        setCountdown()
      }, 1000)
    })

    onBeforeUnmount(() => {
      clearInterval(state.interval)
    })

    const countdown = computed(() => {
      return `${state.d}:${state.h}:${state.m}:${state.s}`
    })

    const formattedCountdown = computed(() => {
      const parts: string[] = []
      if (state.d !== '0') parts.push(`${state.d}d`)
      if (state.h !== '0' || state.d !== '0') parts.push(`${state.h}h`)
      if (state.m !== '0' || state.h !== '0' || state.d !== '0')
        parts.push(`${state.m}m`)
      parts.push(`${state.s}s`)
      return parts.join(' ')
    })

    const isReady = computed(() => {
      return countdown.value === '0:0:0:00' || countdown.value === '0:0:0:0'
    })

    const go = () => {
      if (INFOBAR.urlReady && isReady.value) {
        window.open(INFOBAR.urlReady, '_blank')
      } else {
        window.open(INFOBAR.url, '_blank')
      }
    }

    return {state, isReady, countdown, go, infobar, formattedCountdown}
  },
})
</script>

<style lang="scss">
.infobar {
  position: absolute;
  right: 0;
  left: 0;
  top: 120px;
  width: fit-content;
  margin: 0 auto;
  text-align: center;

  &--active {
    .infobar__ready {
      background: $primary-color-100;
      cursor: pointer;
      transition: transform 0.5s;
      &:hover {
        transform: translateY(-10%);
      }
    }
  }

  &__countdown {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 10px;

    &__textWrapper {
      color: #1a1a1a;
      font-size: 0.9rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
    }

    &__preText {
      color: inherit;
    }

    &__timeBox {
      background: $primary-color-100;
      color: white;
      border-radius: 4px;
      padding: 15px 30px;
      min-width: 250px;
      cursor: pointer;
      transition: transform 0.5s;

      &:hover {
        transform: translateY(-10%);
      }
    }

    &__time {
      font-size: 1.8rem;
      font-weight: 700;
      font-variant-numeric: tabular-nums;
      letter-spacing: 2px;
      color: white;
    }
  }

  &__ready {
    background: $primary-color-100;
    color: white;
    border-radius: 4px;
    padding: 15px 30px;
    min-width: 250px;
    font-size: 1.5rem;
    font-weight: 600;
    cursor: pointer;
  }
}

@media (max-width: 600px) {
  .infobar {
    top: 100px;
    padding: 12px 20px;

    &__countdown {
      &__textWrapper {
        font-size: 0.8rem;
      }

      &__time {
        font-size: 1.5rem;
        letter-spacing: 1.5px;
      }
    }
  }

  .infobar__countdown__preText--desktopOnly {
    display: none !important;
  }
}
</style>

// src/components/infobar/Infobar.tsx
'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faExternalLinkAlt } from '@fortawesome/free-solid-svg-icons';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import { INFOBAR } from '@/lib/data/var';

dayjs.extend(utc);

interface CountdownState {
  d: string;
  h: string;
  m: string;
  s: string;
}

const getInitialCountdown = (): CountdownState => {
  const then = dayjs.utc(INFOBAR.date).valueOf();
  const now = dayjs.utc().valueOf();
  if (then - now < 0) {
    return { d: '0', h: '0', m: '0', s: '0' };
  }
  const diff = then - now;
  const countdown = dayjs.utc(diff);
  const dNum = Math.floor(diff / (1000 * 60 * 60 * 24));
  const hNum = countdown.hour();
  const mNum = countdown.minute();
  const sNum = countdown.second();

  return {
    d: String(dNum),
    h: dNum > 0 ? (hNum < 10 ? '0' : '') + String(hNum) : String(hNum),
    m:
      dNum > 0 || hNum > 0
        ? (mNum < 10 ? '0' : '') + String(mNum)
        : String(mNum),
    s: (sNum < 10 ? '0' : '') + String(sNum),
  };
};

export const Infobar: React.FC = () => {
  const [countdown, setCountdown] = useState<CountdownState>(getInitialCountdown());
  const [showInfobar, setShowInfobar] = useState(true);

  useEffect(() => {
    const interval = setInterval(() => {
      const then = dayjs.utc(INFOBAR.date).valueOf();
      const now = dayjs.utc().valueOf();
      if (then - now < 0) {
        setCountdown({ d: '0', h: '0', m: '0', s: '0' });
        return;
      }
      const diff = then - now;
      const countdownTime = dayjs.utc(diff);
      const dNum = Math.floor(diff / (1000 * 60 * 60 * 24));
      const hNum = countdownTime.hour();
      const mNum = countdownTime.minute();
      const sNum = countdownTime.second();

      setCountdown({
        d: String(dNum),
        h: dNum > 0 ? (hNum < 10 ? '0' : '') + String(hNum) : String(hNum),
        m:
          dNum > 0 || hNum > 0
            ? (mNum < 10 ? '0' : '') + String(mNum)
            : String(mNum),
        s: (sNum < 10 ? '0' : '') + String(sNum),
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const formattedCountdown = useMemo(() => {
    const parts: string[] = [];
    if (countdown.d !== '0') parts.push(`${countdown.d}d`);
    if (countdown.h !== '0' || countdown.d !== '0') parts.push(`${countdown.h}h`);
    if (countdown.m !== '0' || countdown.h !== '0' || countdown.d !== '0')
      parts.push(`${countdown.m}m`);
    parts.push(`${countdown.s}s`);
    return parts.join(' ');
  }, [countdown]);

  const isReady = useMemo(() => {
    const countdownString = `${countdown.d}:${countdown.h}:${countdown.m}:${countdown.s}`;
    return countdownString === '0:0:0:00' || countdownString === '0:0:0:0';
  }, [countdown]);

  const go = () => {
    if (INFOBAR.urlReady && isReady) {
      window.open(INFOBAR.urlReady, '_blank');
    } else {
      window.open(INFOBAR.url, '_blank');
    }
  };

  if (!showInfobar || (isReady && INFOBAR.hideWhenReady)) {
    return null;
  }

  return (
    <div
      className="w-fit mx-auto -mt-20 mb-[50px] text-center max-h-[800px]:mt-0 max-h-[800px]:mb-[30px] max-[600px]:mt-0 max-[600px]:mb-5"
    >
      {!isReady && (
        <div className="flex flex-col items-center justify-center gap-2.5">
          <div className="text-[#1a1a1a] text-[0.9rem] font-bold uppercase tracking-[1px] max-[600px]:text-[0.8rem]">
            {INFOBAR.titleDesktopOnly && (
              <span className="max-[600px]:hidden">
                {INFOBAR.titleDesktopOnly}
              </span>
            )}
            <span>{INFOBAR.title}</span>
          </div>
          <div
            className="bg-[#e31337] text-white rounded px-[30px] py-[15px] min-w-[250px] cursor-pointer transition-transform duration-500 hover:-translate-y-[10%] flex items-center justify-center gap-3 max-[600px]:px-5 max-[600px]:py-3"
            onClick={go}
          >
            <span className="text-[1.8rem] font-bold font-variant-numeric-tabular-nums tracking-[2px] text-white max-[600px]:text-2xl max-[600px]:tracking-[1.5px]">
              {formattedCountdown}
            </span>
            <FontAwesomeIcon
              className="h-2.5 w-2.5 text-white opacity-80"
              icon={faExternalLinkAlt}
            />
          </div>
        </div>
      )}
      {isReady && (
        <div
          className="bg-[#e31337] text-white rounded px-[30px] py-[15px] min-w-[250px] text-2xl font-semibold cursor-pointer transition-transform duration-500 hover:-translate-y-[10%]"
          onClick={go}
        >
          {INFOBAR.titleReady}
        </div>
      )}
    </div>
  );
};
