// src/components/app/app.vue
<template>
  <div
    class="app"
    :class="`app--${item.name} app--type-${appType} ${
      move && !detailed ? 'app--shouldMove' : ''
    } ${detailed ? 'app--detailed' : ''}`"
  >
    <a
      v-if="!openModal && !detailed && !openDetailed"
      :href="item.website"
      target="_blank"
      rel="nofollow noopener noreferrer"
      class="app__inner"
      :class="{'app__inner--hover': hover}"
      @mouseenter="hover = true"
      @mouseleave="hover = false"
    >
      <div class="app__image">
        <img :src="getImage(item.image)" />
      </div>
    </a>

    <div
      v-else
      class="app__inner"
      :class="{'app__inner--hover': hover}"
      @mouseenter="hover = true"
      @mouseleave="hover = false"
      @click="onClick"
    >
      <div class="app__image">
        <img :src="getImage(item.image)" />
      </div>
    </div>

    <div class="app__right">
      <div class="app__topContainer">
        <a
          v-if="showName || detailed"
          :href="item.website"
          target="_blank"
          rel="nofollow noopener noreferrer"
          class="app__name"
          :class="{'app__name--hover': hover}"
          @mouseenter="hover = true"
          @mouseleave="hover = false"
          >{{ item.name
          }}<fa-icon
            v-if="!detailed && !openDetailed && !openModal"
            class="app__name__icon"
            :icon="['fas', 'external-link-alt']"
          ></fa-icon
        ></a>
        <div v-if="detailed || showTypes" class="app__typeContainer">
          <AppType v-for="t in item.types" :key="t" :app-type="t" />
        </div>
        <div
          v-if="detailed && stats && stats.dau && stats.dau.last_month > 10"
          class="app__monthlyUsers"
        >
          {{ `${formatToUnits(stats.dau.last_month)} Monthly Users` }}
        </div>
      </div>

      <div v-if="detailed" class="app__description">{{ item.description }}</div>

      <div v-if="item.os" class="app__icons">
        <Icon
          v-for="os in item.os"
          :key="os.name"
          class="app__icon"
          :icon="os.icon"
          :tooltip="os.name"
          :height="18"
        />
      </div>
      <a
        v-if="item.github || item.gitlab"
        :href="item.github || item.gitlab"
        target="_blank"
        rel="nofollow noopener noreferrer"
        class="app__git"
        >{{ 'Open Source'
        }}<fa-icon
          class="app__git__icon"
          :icon="['fas', 'external-link-alt']"
        ></fa-icon
      ></a>
      <div v-if="item.closedSource" class="app__git">
        {{ 'Closed Source'
        }}<fa-icon class="app__git__icon" :icon="['fas', 'times']"></fa-icon>
      </div>
      <div v-if="detailed" class="app__launch">
        <a
          :href="item.website"
          target="_blank"
          rel="nofollow noopener noreferrer"
          style="color: white"
          >Website</a
        >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent, ref, computed} from '@nuxtjs/composition-api'
import {formatToUnits} from '~/helpers/util'

export default defineComponent({
  props: {
    item: {
      type: Object,
      default: () => {},
    },
    appType: String,
    move: {
      type: Boolean,
      default: true,
    },
    showName: {
      type: Boolean,
      default: true,
    },
    showTypes: {
      type: Boolean,
      default: false,
    },
    openModal: Boolean,
    openDetailed: Boolean,
    detailed: Boolean,
  },

  setup(_props, {root}) {
    const hover = ref(false)
    const dict = {threespeak: '3speak'}
    const statsApp = root.$accessor.statsAppsData.filter(
      (d) => d.name === (dict[_props.item.id] || _props.item.id),
    )[0]
    let stats: any = {}
    if (statsApp) stats = computed(() => statsApp)
    const getImage = (image) => {
      try {
        return require(`~/assets/images/apps/${image}`)
      } catch (error) {
        return ''
      }
    }
    return {getImage, hover, stats}
  },
  methods: {
    onClick() {
      if (this.$props.openDetailed || this.$accessor.activeEco.id) {
        this.$accessor.setActiveEco(this.$props.item as any)
        if (this.$props.openDetailed) {
          // this.$router.replace(`/eco/${this.$props.item.id}`)
        }
      } else {
        this.$accessor.setActiveEco(this.$props.item as any)
        this.$modal.show('modal-eco')
      }
    },
    formatToUnits(v) {
      return formatToUnits(v)
    },
  },
})
</script>

<style lang="scss">
.app {
  display: flex;
  flex-flow: column;
  align-items: center;
  justify-content: center;
  margin: 15px 30px;
  cursor: pointer;

  &__inner {
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 15%;
    background: #e2e2ec;
    height: 110px;
    width: 110px;
    padding: 12px;
    margin-bottom: 8px;
    transition: transform 0.5s;
  }

  &__icons {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 2px;
  }

  &__icon {
    margin: 4px;
  }

  &__name {
    display: flex;
    align-items: center;
    margin-top: 2px;
    margin-bottom: 6px;
    font-size: 1rem;
    transition: all ease-in 0.1s;

    &__icon {
      height: 8px;
      margin-left: 5px;
    }
  }

  &--shouldMove {
    .app__name {
      &:hover,
      &--hover {
        color: $primary-color-100;
      }
    }

    .app__inner {
      &:hover,
      &--hover {
        transform: translateY(-10%);
      }
    }
  }

  &__git {
    display: flex;
    align-items: center;
    margin-top: 4px;
    font-size: 0.88rem;
    opacity: 0.5;
    transition: all ease-in 0.1s;
    &:hover {
      color: $primary-color-100;
    }

    &__icon {
      height: 7px;
      margin-left: 5px;
    }
  }

  &__image {
    display: flex;
    height: 100%;
    width: 100%;
    img {
      height: 100%;
      width: 100%;
      border-radius: 15%;
    }
  }

  &--Engrave {
    .app__image {
      height: initial;
      img {
        border-radius: 0;
      }
    }
  }

  &--DLease {
    .app__image {
      display: flex;
      justify-content: center;
      img {
        width: initial;
      }
    }
  }

  .app__right {
    display: flex;
    flex-flow: column;
    align-items: center;
  }

  .app__topContainer {
    display: flex;
    flex-flow: column wrap;
    align-items: center;
  }

  .app__typeContainer {
    display: flex;
    align-items: center;
    margin-bottom: 6px;
    .app-type {
      margin-left: 8px;

      &:nth-of-type(1) {
        margin-left: 0;
      }
    }
  }

  .app__monthlyUsers {
    padding: 5px 10px;
    margin-left: 15px;
    background: #e2e2ec;
    border-radius: 5px;
    font-size: 0.8rem;
    cursor: default;
    margin-bottom: 6px;
  }

  &--detailed {
    flex-flow: row wrap;
    align-items: flex-start;
    justify-content: flex-start;
    cursor: initial;

    .app__name {
      font-size: 1.5rem;
      font-weight: 600;
    }

    .app__right {
      display: flex;
      flex-flow: column;
      align-items: flex-start;
      margin-top: 10px;
      margin-left: 20px;
      flex: 1;
    }

    .app__inner {
    }

    .app__topContainer {
      flex-flow: row wrap;
      margin-bottom: 5px;
    }

    .app__typeContainer {
      margin-left: 12px;
      margin-top: -2px;
    }

    .app__launch {
      padding: 8px 20px;
      cursor: pointer;
      border-radius: 5px;
      background: #757575;
      width: fit-content;
      color: white;
      margin-top: 14px;
      &:hover {
        background: #5f5f5f;
      }
    }
  }
}

@media (max-width: 525px) {
  .app {
    margin: 20px 20px 40px 20px;
  }

  .app__monthlyUsers {
    margin-left: 0 !important;
  }
}

@media (max-width: 425px) {
  .app {
    margin: 15px 15px 30px 15px;
  }
}
</style>

// src/components/app/App.tsx
'use client';

import React, { useState, useMemo } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faExternalLinkAlt, faTimes } from '@fortawesome/free-solid-svg-icons';
import { useAssets } from '@/hooks/useAssets';
import { useMainStore } from '@/store/useMainStore';
import { formatToUnits } from '@/lib/data/util';
import { AppType } from './AppType';
import { Icon } from '../Icon';
import type { IEcoItem, IWallet } from '@/types';

interface AppProps {
  item: IEcoItem | IWallet;
  appType?: string;
  move?: boolean;
  showName?: boolean;
  showTypes?: boolean;
  openModal?: boolean;
  openDetailed?: boolean;
  detailed?: boolean;
  style?: React.CSSProperties;
  size?: number;
}

export const App: React.FC<AppProps> = ({
  item,
  appType = '',
  move = false,
  showName = false,
  showTypes = false,
  openModal = false,
  openDetailed = false,
  detailed = false,
  style,
  size = 110
}) => {
  const { getImage } = useAssets();
  const [hover, setHover] = useState(false);

  const statsAppsData = useMainStore(state => state.statsAppsData);
  const activeEco = useMainStore(state => state.activeEco);
  const setActiveEco = useMainStore(state => state.setActiveEco);

  const dict: Record<string, string> = { threespeak: '3speak' };

  const stats = useMemo(() => {
    return statsAppsData.find(
      (d: any) => d.name === (dict[item.id] || item.id)
    );
  }, [statsAppsData, item.id]);

  const getAppImage = (image: string) => {
    return getImage(`apps/${image}`);
  };

  const getWebsiteUrl = () => {
    if (!item.website) {
      return '#';
    }
    if (typeof item.website === 'string') {
      return item.website;
    }
    // For IWallet with browser-specific URLs, prefer chrome, then firefox, then safari
    return item.website.chrome || item.website.firefox || item.website.safari || '#';
  };

  const onClick = () => {
    if (openDetailed || activeEco.id) {
      setActiveEco(item as IEcoItem);
      if (openDetailed) {
        // router.replace(`/eco/${item.id}`)
      }
    } else {
      setActiveEco(item as IEcoItem);
      // Modal will show automatically
    }
  };

  const isEngrave = item.name === 'Engrave';
  const isDLease = item.name === 'DLease';

  const baseClasses = `flex flex-col items-center justify-center cursor-pointer ${
    detailed ? 'flex-row flex-wrap items-start justify-start cursor-default mx-[30px] my-[15px]' : ''
  }`;

  const innerClasses = `flex justify-center items-center rounded-[15%] bg-[#e2e2ec] p-3 mb-2 transition-transform duration-500 ${
    move && !detailed && hover ? '-translate-y-[10%]' : ''
  }`;

  const innerContent = (
    <div
      className={`flex ${isEngrave ? 'h-auto' : ''} ${isDLease ? 'justify-center' : ''}`}
      style={{ height: `${size}px`, width: `${size}px` }}
    >
      <img
        src={getAppImage(item.image)}
        alt={item.name}
        className={`h-full w-full ${isEngrave ? '' : 'rounded-[15%]'} ${isDLease ? 'w-auto' : ''}`}
      />
    </div>
  );

  return (
    <div className={baseClasses} style={style}>
      {!openModal && !detailed && !openDetailed ? (
        <a
          href={getWebsiteUrl()}
          target="_blank"
          rel="nofollow noopener noreferrer"
          className={innerClasses}
          onMouseEnter={() => setHover(true)}
          onMouseLeave={() => setHover(false)}
        >
          {innerContent}
        </a>
      ) : (
        <div
          className={innerClasses}
          onMouseEnter={() => setHover(true)}
          onMouseLeave={() => setHover(false)}
          onClick={onClick}
        >
          {innerContent}
        </div>
      )}

      <div className={`flex flex-col items-center ${detailed ? 'items-start mt-2.5 ml-5 flex-1' : ''}`}>
        <div className={`flex flex-col flex-wrap items-center ${detailed ? 'flex-row mb-[5px]' : ''}`}>
          {(showName || detailed) && (
            <a
              href={getWebsiteUrl()}
              target="_blank"
              rel="nofollow noopener noreferrer"
              className={`flex items-center mt-0.5 mb-1.5 text-base transition-all ease-in duration-100 ${
                move && !detailed && hover ? 'text-[#e31337]' : ''
              } ${detailed ? 'text-2xl font-semibold' : ''}`}
              onMouseEnter={() => setHover(true)}
              onMouseLeave={() => setHover(false)}
            >
              {item.name}
              {!detailed && !openDetailed && !openModal && (
                <FontAwesomeIcon
                  className="h-2 ml-[5px]"
                  icon={faExternalLinkAlt}
                />
              )}
            </a>
          )}
          {(detailed || showTypes) && (
            <div className={`flex items-center mb-1.5 [&>*:not(:first-child)]:ml-2 ${detailed ? 'ml-3 -mt-0.5' : ''}`}>
              {item.types?.map((t, index) => (
                <AppType key={index} appType={t} />
              ))}
            </div>
          )}
          {detailed && stats && stats.dau && stats.dau.last_month > 10 && (
            <div className="py-[5px] px-2.5 ml-[15px] bg-[#e2e2ec] rounded-[5px] text-[0.8rem] cursor-default mb-1.5 max-[525px]:ml-0">
              {`${formatToUnits(stats.dau.last_month)} Monthly Users`}
            </div>
          )}
        </div>

        {detailed && 'description' in item && item.description && (
          <div>{item.description}</div>
        )}

        {'os' in item && item.os && (
          <div className="flex justify-center items-center mb-0.5">
            {item.os.map((os, index) => (
              <Icon
                key={index}
                icon={os.icon}
                tooltip={os.name}
                height={18}
              />
            ))}
          </div>
        )}

        {('github' in item || 'gitlab' in item) && (item.github || item.gitlab) && (
          <a
            href={item.github || item.gitlab}
            target="_blank"
            rel="nofollow noopener noreferrer"
            className="flex items-center mt-1 text-[0.88rem] opacity-50 transition-all ease-in duration-100 hover:text-[#e31337]"
          >
            Open Source
            <FontAwesomeIcon
              className="h-[7px] ml-[5px]"
              icon={faExternalLinkAlt}
            />
          </a>
        )}

        {'closedSource' in item && item.closedSource && (
          <div className="flex items-center mt-1 text-[0.88rem] opacity-50">
            Closed Source
            <FontAwesomeIcon className="h-[7px] ml-[5px]" icon={faTimes} />
          </div>
        )}

        {detailed && (
          <div className="py-2 px-5 cursor-pointer rounded-[5px] bg-[#757575] w-fit text-white mt-[14px] hover:bg-[#5f5f5f]">
            <a
              href={getWebsiteUrl()}
              target="_blank"
              rel="nofollow noopener noreferrer"
              className="text-white"
            >
              Website
            </a>
          </div>
        )}
      </div>
    </div>
  );
};
