// apps/web/src/components/app/EcoDetailed.tsx
'use client';

import React from 'react';
import { useRouter, usePathname } from '@/i18n/routing';
import { useMainStore } from '@/store/useMainStore';
import { Button } from '@/components/ui/button';
import { App } from './App';

export const EcoDetailed: React.FC = () => {
  const router = useRouter();
  const pathname = usePathname();

  const activeEco = useMainStore(state => state.activeEco);
  const getSimilarEco = useMainStore(state => state.getSimilarEco);
  const getOtherEco = useMainStore(state => state.getOtherEco);

  const similarEco = getSimilarEco();
  const otherEco = getOtherEco();

  const exploreEco = () => {
    router.push('/eco');
  };

  const isEcoPage = pathname.endsWith('/eco') || pathname.includes('/eco/');

  return (
    <div className="pt-6">
      <div className="!m-0 py-[25px] px-10 !mb-[15px] bg-[#f0f0f8]">
        <App
          item={activeEco}
          detailed={true}
        />
      </div>
      <div>
        <h3 className="text-2xl font-bold leading-normal mb-2.5 pl-10">Similar Apps</h3>
        <div className="flex flex-row flex-wrap p-0 pr-10 pb-[5px] pl-[30px] [&>div]:!mx-2 [&>div]:!my-1 [&>div>div:last-child]:!hidden">
          {similarEco.map((eco) => (
            <App
              key={eco.id}
              item={eco}
              detailed={false}
              move={true}
              showName={false}
              openModal={true}
              appType="eco"
              size={40}
              style={{
                opacity: eco.id === activeEco.id ? '0.333' : '1'
              }}
            />
          ))}
        </div>
      </div>
      {!isEcoPage && (
        <div>
          <div className="flex mb-2.5">
            <h3 className="text-2xl font-bold leading-normal m-0 pl-10">
              Other Apps
            </h3>
            <Button
              variant="outline"
              className="ml-[15px] py-1.5 px-[18px]"
              onClick={exploreEco}
            >
              Explore Ecosystem
            </Button>
          </div>
          <div className="flex flex-row flex-wrap p-0 pr-10 pb-[5px] pl-[30px] [&>div]:!mx-2 [&>div]:!my-1 [&>div>div:last-child]:!hidden">
            {otherEco.map((eco) => (
              <App
                key={eco.id}
                item={eco}
                detailed={false}
                move={true}
                showName={false}
                openModal={true}
                appType="eco"
                size={40}
                style={{
                  opacity: eco.id === activeEco.id ? '0.333' : '1'
                }}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

// src/components/app/ecoDetailed.vue
<template>
  <div class="eco-detailed">
    <App
      class="eco-detailed__active"
      :item="$accessor.activeEco"
      :detailed="true"
    />
    <div>
      <h3 class="eco-detailed__otherTitle">Similar Apps</h3>
      <div class="eco-detailed__otherContainer">
        <App
          v-for="eco in $accessor.similarEco"
          :key="eco.id"
          :item="eco"
          :detailed="false"
          :move="true"
          :show-name="false"
          :open-modal="true"
          app-type="eco"
          :style="`opacity: ${
            eco.id === $accessor.activeEco.id ? '0.333' : '1'
          }`"
        />
      </div>
    </div>
    <div v-if="$route.name !== 'eco' && $route.name !== 'eco-app'">
      <div style="display: flex; margin-bottom: 10px">
        <h3 class="eco-detailed__otherTitle" style="margin: 0">Other Apps</h3>
        <el-button
          type="primary"
          style="margin-left: 15px; padding: 6px 18px"
          plain
          @click="exploreEco"
          >Explore Ecosystem</el-button
        >
      </div>
      <div class="eco-detailed__otherContainer">
        <App
          v-for="eco in $accessor.otherEco"
          :key="eco.id"
          :item="eco"
          :detailed="false"
          :move="true"
          :show-name="false"
          :open-modal="true"
          app-type="eco"
          :style="`opacity: ${
            eco.id === $accessor.activeEco.id ? '0.333' : '1'
          }`"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent, onBeforeUnmount} from '@nuxtjs/composition-api'
import {IEcoItem} from '~/types'
import {ECOSYSTEM} from '~/helpers/ecosystem'

export default defineComponent({
  name: 'EcoDetailed',
  props: {},
  setup() {
    return {}
  },
  methods: {
    exploreEco() {
      this.$modal.hide('modal-eco')
      this.$router.push('/eco')
    },
  },
})
</script>

<style lang="scss">
.eco-detailed {
  &__active {
    margin: 0 !important;
    padding: 25px 40px;
    margin-bottom: 15px !important;
    background: $color-0;
  }

  &__otherTitle {
    font-size: 1.5rem;
    margin-bottom: 10px;
  }

  &__otherTitle,
  &__otherContainer {
    padding-left: 40px;
  }
  &__otherContainer {
    display: flex;
    flex-flow: row wrap;
    padding: 0 40px 5px 30px;

    .app {
      margin: 0 12px 8px 0;
    }

    .app__inner {
      height: 40px;
      width: 40px;
    }
  }
}
</style>
