// src/app/[locale]/eco/page.tsx
'use client';

import React, { Suspense, useState, useEffect, useMemo } from 'react';
import { useSearchParams } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { useRouter } from '@/i18n/routing';
import { useMainStore } from '@/store/useMainStore';
import { ECOSYSTEM, STATISTIC_WEBSITES, TYPE_COLORS, HIVE_PROJECTS } from '@/lib/data/var';
import { EcoType, IEcoItem } from '@/types';
import { App } from '@/components/app/App';
import { AppType } from '@/components/app/AppType';
import { StatWebsite } from '@/components/statWebsite/StatWebsite';
import { ModalEco } from '@/components/modal/ModalEco';

function EcoContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const t = useTranslations();
  const [filteredEco, setFilteredEco] = useState<IEcoItem[]>([]);

  const filterParam = searchParams.get('t');

  const appTypes = useMemo(() =>
    Object.keys(TYPE_COLORS)
      .filter((c) => {
        return ECOSYSTEM.find((e) => e.types.includes(c as any));
      })
      .map((c) => {
        return {
          value: c,
          count: ECOSYSTEM.filter((e) => e.types.includes(c as any)).length,
        };
      }),
    []
  );

  const getFilteredEco = (key: string | null) => {
    setFilteredEco(ECOSYSTEM.filter((e) => !key || e.types.includes(key as EcoType)));
  };

  // Initialize on mount
  useEffect(() => {
    getFilteredEco(filterParam);
  }, []);

  // Update when filter changes
  useEffect(() => {
    getFilteredEco(filterParam);
  }, [filterParam]);

  const filterEco = (key: string) => {
    if (filterParam === key) {
      router.push('/eco');
    } else {
      router.push(`/eco?t=${key}`);
    }
  };

  return (
    <div className="flex justify-center w-full min-h-[calc(100vh-80px)] py-20 px-5">
      <div className="flex flex-col items-center w-full max-w-[1200px]">
        {/* Hero Section */}
        <div className="flex flex-col items-center text-center mb-16">
          <h1 className="text-[4rem] font-bold leading-tight mb-6 max-[600px]:text-[3rem]">
            {t('eco.title')}<span className="text-[#e31337]">.</span>
          </h1>
          <p className="text-xl max-w-[700px] text-[#555] leading-relaxed">
            {t('eco.text')}
          </p>
        </div>

        {/* Filter Types */}
        <div className="flex flex-row flex-wrap justify-center gap-3 mb-12">
          {appTypes.map((appType) => (
            <AppType
              key={appType.value}
              className={
                filterParam && filterParam !== appType.value
                  ? 'opacity-40 hover:opacity-75'
                  : ''
              }
              appType={appType.value}
              count={appType.count}
              onClick={() => filterEco(appType.value)}
            />
          ))}
        </div>

        <ModalEco />

        {/* Apps Grid */}
        <div className="grid grid-cols-[repeat(auto-fill,minmax(170px,1fr))] justify-items-center w-full gap-x-5 gap-y-8 mb-16">
          {filteredEco.map((eco) => (
            <App
              key={eco.id}
              item={eco}
              openModal={true}
              move={true}
              showName={true}
              showTypes={true}
              appType="eco"
            />
          ))}
        </div>

        {/* More Projects Section */}
        <div className="flex flex-col items-center text-center mt-12 mb-16">
          <h2 className="text-[2.8rem] font-bold leading-tight mb-4">
            But wait, there's more<span className="text-[#e31337]">...</span>
          </h2>
          <p className="text-xl text-[#555] leading-relaxed mb-6">
            Over <span className="font-bold text-black">190 projects</span> have been BUIDL'd by the Hive community. You
            can view all of them via HiveProjects.io
          </p>
          <StatWebsite item={HIVE_PROJECTS} transparent={true} />
        </div>

        {/* Statistics Section */}
        <div className="flex flex-col items-center text-center w-full mt-16">
          <h2 className="text-[2.8rem] font-bold leading-tight mb-4">
            {t('eco.subTitle')}<span className="text-[#e31337]">.</span>
          </h2>
          <p className="text-xl text-[#555] leading-relaxed mb-8">{t('eco.subText')}</p>
          <div className="flex flex-row flex-wrap justify-center gap-8 w-full">
            {STATISTIC_WEBSITES.map((site) => (
              <StatWebsite key={site.id} item={site} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function EcoPage() {
  return (
    <Suspense fallback={<div className="text-center py-20">Loading...</div>}>
      <EcoContent />
    </Suspense>
  );
}

// src/pages/eco.vue
<template>
  <div class="eco">
    <div class="eco__inner">
      <div class="eco__first">
        <h1 class="eco__title">{{ $t(`eco.title`) }}</h1>
        <p class="eco__text">
          {{ $t(`eco.text`) }}
        </p>
      </div>
      <div class="eco__types">
        <AppType
          v-for="appType in appTypes"
          :key="appType.value"
          :class="{
            'eco__type--inactive':
              $route.query.t && $route.query.t !== appType.value,
          }"
          :app-type="appType.value"
          :count="appType.count"
          @click.native="filterEco(appType.value)"
        />
      </div>
      <ModalEco />

      <div class="eco__apps">
        <!-- <EcoDetailed
          v-if="$route.name === 'eco-app' || $accessor.activeEco.id"
        /> -->
        <App
          v-for="eco in filteredEco"
          :key="eco.id"
          :item="eco"
          :open-modal="true"
          :move="true"
          :show-name="true"
          :show-types="true"
          app-type="eco"
        />
      </div>
      <h2 style="margin-top: 40px">But wait, there's more...</h2>
      <p>
        Over <b>190 projects</b> have been BUIDL'd by the Hive community. You
        can view all of them via HiveProjects.io
      </p>
      <StatWebsite :item="HIVE_PROJECTS" :transparent="true" />

      <h2 class="eco__subTitle">{{ $t(`eco.subTitle`) }}</h2>
      <p class="eco__subText">
        {{ $t(`eco.subText`) }}
      </p>
      <div class="eco__statistics">
        <StatWebsite
          v-for="site in STATISTIC_WEBSITES"
          :key="site.id"
          :item="site"
        />
      </div> 
    </div>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  useRouter,
  useRoute,
  watch,
  reactive,
  ref,
  computed,
  useAsync,
} from '@nuxtjs/composition-api'
import {
  ECOSYSTEM,
  STATISTIC_WEBSITES,
  TYPE_COLORS,
  HIVE_PROJECTS,
} from '../helpers/var'
import {routerPush} from '~/helpers/util'
import EcoDetailed from '~/components/app/ecoDetailed.vue'

export default defineComponent({
  name: 'Eco',
  components: {EcoDetailed},
  props: {},
  setup(_prop, {root}) {
    const route = useRoute()
    useAsync(() => {
      if (route.value.name === 'eco-app') {
        root.$accessor.setActiveEco(
          ECOSYSTEM.filter((e) => e.id === route.value.params.app)[0],
        )
      }
    })
    const appTypes = computed(() =>
      Object.keys(TYPE_COLORS)
        .filter((c) => {
          return ECOSYSTEM.filter((e) => e.types.includes(c as any))[0]
        })
        .map((c) => {
          return {
            value: c,
            count: ECOSYSTEM.filter((e) => e.types.includes(c as any)).length,
          }
        }),
    )
    const filteredEco = ref([] as any)

    const getFilteredEco = (key) => {
      filteredEco.value = ECOSYSTEM.filter((e) => !key || e.types.includes(key))
    }

    getFilteredEco(route.value.query.t)
    watch(
      () => route.value.query.t,
      (newT) => getFilteredEco(newT),
    )
    return {
      filteredEco,
      appTypes,
      ECOSYSTEM,
      STATISTIC_WEBSITES,
      HIVE_PROJECTS,
    }
  },
  methods: {
    async filterEco(key: string) {
      if (this.$route.query.t === key) {
        await routerPush(this, `/eco`)
      } else {
        await routerPush(this, `/eco?t=${key}`)
      }
    },
  },
})
</script>

<style lang="scss" scoped>
.eco {
  display: flex;
  align-items: center;
  margin-bottom: 150px;
  &__inner {
    display: flex;
    flex-flow: column;
    align-items: center;
    padding: 0 30px;
    width: calc(100% - 60px);
  }
  &__first {
    margin-top: 100px;
    padding: 0 0 20px 0;
    max-width: 720px;
    min-height: 120px;
    width: 100%;
    text-align: center;
  }

  &__text {
    max-width: 820px;
    margin-bottom: 0;
  }

  &__types {
    display: flex;
    flex-flow: row wrap;
    margin-top: 20px;
    margin-bottom: 15px;
    .app-type {
      margin-right: 12px;
      margin-bottom: 8px;
    }
  }

  &__type {
    &--inactive {
      opacity: 0.333;
      &:hover {
        opacity: 0.75;
      }
    }
  }

  h1 {
    text-align: center;
  }

  h3 {
    font-size: 1.5rem;
  }

  &__apps {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
    max-width: 1000px;
  }

  &__subTitle {
    margin: 60px 0 15px 0;
  }

  &__statistics {
    display: flex;
    flex-flow: row wrap;
    justify-content: space-evenly;
    max-width: 800px;
    margin-top: 20px;
  }
}

@media (max-width: 700px) {
  .eco__first {
    margin-top: 100px;
  }
}

@media (max-width: 600px) {
  .eco {
    &__first {
      margin-top: 20px;
    }

    &__types {
      justify-content: space-evenly;
    }
  }
}
</style>
