// src/app/[locale]/wallets/page.tsx
'use client';

import React from 'react';
import { useTranslations } from 'next-intl';
import { App } from '@/components/app/App';
import { WALLETS } from '@/lib/data/var';

export default function WalletsPage() {
  const t = useTranslations();

  return (
    <div className="flex justify-center w-full min-h-[calc(100vh-80px)] py-20 px-5">
      <div className="flex flex-col items-center w-full max-w-[1200px]">
        {/* Hero Section */}
        <div className="flex flex-col items-center text-center mb-16">
          <h1 className="text-[4rem] font-bold leading-tight mb-6 max-[600px]:text-[3rem]">
            {t('wallets.title')}<span className="text-[#e31337]">.</span>
          </h1>
          <p className="text-xl max-w-[700px] text-[#555] leading-relaxed">
            {t('wallets.text')}
          </p>
        </div>

        {/* Wallets Grid */}
        <div className="flex flex-row flex-wrap items-start justify-center w-full gap-5">
          {WALLETS.map((wallet) => (
            <App key={wallet.id} item={wallet} />
          ))}
        </div>
      </div>
    </div>
  );
}

// src/pages/wallets.vue
<template>
  <div class="wallets">
    <div class="wallets__inner">
      <div class="wallets__first">
        <h1 class="wallets__title">{{ $t(`wallets.title`) }}</h1>
        <p class="wallets__text">
          {{ $t(`wallets.text`) }}
        </p>
      </div>
      <div class="wallets__apps">
        <App v-for="wallet in WALLETS" :key="wallet.id" :item="wallet" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@vue/composition-api'
import {WALLETS} from '../helpers/var'
import Logo from '~/components/logo/logo.vue'
import App from '~/components/app/app.vue'

export default defineComponent({
  components: {Logo, App},
  props: {},
  setup() {
    return {WALLETS}
  },
})
</script>

<style lang="scss" scoped>
.wallets {
  display: flex;
  align-items: center;
  margin-bottom: 150px;
  &__inner {
    display: flex;
    flex-flow: column;
    align-items: center;
    align-items: center;
    padding: 0 30px;
    width: calc(100% - 60px);
  }
  &__first {
    margin-top: 100px;
    padding: 0 0 20px 0;
    max-width: 720px;
    min-height: 160px;
    text-align: center;
  }

  &__text {
    max-width: 820px;
  }

  h2 {
    font-size: 3.8rem;
  }

  h3 {
    font-size: 1.5rem;
  }

  &__apps {
    display: flex;
    flex-flow: row wrap;
    align-items: flex-start;
    justify-content: center;
    max-width: 900px;
  }
}

@media (max-width: 700px) {
  .wallets__first {
    margin-top: 100px;
  }
}

@media (max-width: 600px) {
  .wallets__first {
    margin-top: 20px;
  }
}
</style>
