// src/components/app/appType.vue
<template>
  <div
    class="app-type"
    :class="{'app-type--withCount': Boolean(count)}"
    :style="`background: ${
      true ? TYPE_COLORS[appType].background : 'rgb(222 222 236)'
    }; color:  ${true ? TYPE_COLORS[appType].text : 'rgb(96 96 110)'}`"
  >
    {{ appType }}
    <span v-if="count">({{ count }})</span>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@nuxtjs/composition-api'
import {TYPE_COLORS} from '~/helpers/ecosystem'
export default defineComponent({
  props: {
    appType: {
      type: String,
      default: 'app',
    },
    count: Number,
  },

  setup() {
    return {TYPE_COLORS}
  },
})
</script>

<style lang="scss">
.app-type {
  padding: 5px;
  border-radius: 6px;
  text-transform: uppercase;
  font-size: 0.7rem;
  font-weight: 600;
  cursor: pointer;

  &--withCount {
    font-size: 1.1rem;
    padding: 7px 15px;
  }
}

@media (max-width: 600px) {
  .app-type {
    &--withCount {
      font-size: 0.8rem;
    }
  }
}
</style>

// apps/web/src/components/app/AppType.tsx
import React from 'react';
import { TYPE_COLORS } from '@/lib/data/ecosystem';

interface AppTypeProps extends React.HTMLAttributes<HTMLDivElement> {
  appType?: string;
  count?: number;
}

export const AppType: React.FC<AppTypeProps> = ({
  appType = 'app',
  count,
  className,
  onClick,
  ...props
}) => {
  const colors = TYPE_COLORS[appType as keyof typeof TYPE_COLORS] || {
    background: 'rgb(222 222 236)',
    text: 'rgb(96 96 110)'
  };

  return (
    <div
      className={`app-type p-[5px] rounded-md uppercase text-[0.7rem] font-semibold cursor-pointer transition-opacity ${
        count ? 'text-[1.1rem] py-[7px] px-[15px] max-[600px]:text-[0.8rem]' : ''
      } ${className || ''}`}
      style={{
        background: colors.background,
        color: colors.text
      }}
      onClick={onClick}
      {...props}
    >
      {appType}
      {count && <span className="ml-1">({count})</span>}
    </div>
  );
};
