// apps/web/src/components/video/Video.tsx
import React from 'react';
import { useAssets } from '@/hooks/useAssets';

export const Video: React.FC = () => {
  const { getVideo } = useAssets();

  return (
    <video className="w-full -mt-8 border border-black rounded-[10px] max-w-[640px] md:mt-10 md:mb-2.5" controls>
      <source src={getVideo('marketing.mp4')} type="video/mp4" />
    </video>
  );
};

// src/components/video/video.vue
<template>
  <video class="video" controls>
    <source src="~/assets/videos/marketing.mp4" type="video/mp4">
  </video>
</template>

<script lang="ts">
import {defineComponent} from '@nuxtjs/composition-api'
export default defineComponent({
  setup() {
    return {}
  },
})
</script>

<style lang="scss">
.video {
  width: auto;
  height: auto;
}
</style>
