// src/components/updates/updates.vue
<template>
  <div class="updates">
    <h2 style="text-align: center; margin-bottom: 40px">Newest Updates</h2>
    <UpdatesUpdate class="updates__update" :item="UPDATES[0]" :big="true" />

    <div class="updates__smaller">
      <UpdatesUpdate
        v-for="update in UPDATES.slice(1, UPDATES.length)"
        :key="update.title"
        class="updates__update"
        :item="update"
      />
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from '@nuxtjs/composition-api'
import {UPDATES} from '~/helpers/updates'

export default defineComponent({
  setup() {
    return {
      UPDATES: UPDATES.map((v) => {
        if (v.video) {
          v.video = v.video
            .replace('youtube.', 'youtube-nocookie.')
            .replace('youtu.be/', 'www.youtube-nocookie.com/embed/')
            .replace('/watch?v=', '/embed/')
            .replace('&t=', '?start=')
        }
        return v
      }),
    }
  },
})
</script>

<style lang="scss">
.updates {
  display: flex;
  flex-flow: column nowrap;
  align-items: center;
  max-width: 1200px;
  width: 100%;

  &__smaller {
    display: flex;
    width: 100%;
    flex-flow: row wrap;
    justify-content: center;

    .updates__update {
      margin: 10px 15px;
    }
  }
}
</style>

// apps/web/src/components/updates/Updates.tsx
import React, { useMemo } from 'react';
import { UPDATES } from '@/lib/data/updates';
import { UpdatesUpdate } from './UpdatesUpdate';

export const Updates: React.FC = () => {
  const UPDATES_PROCESSED = useMemo(() => {
    return UPDATES.map((v) => {
      if (v.video) {
        v.video = v.video
          .replace('youtube.', 'youtube-nocookie.')
          .replace('youtu.be/', 'www.youtube-nocookie.com/embed/')
          .replace('/watch?v=', '/embed/')
          .replace('&t=', '?start=');
      }
      return v;
    });
  }, []);

  return (
    <div className="flex flex-col flex-nowrap items-center max-w-[1200px] w-full">
      <h2 className="text-center mb-10">Newest Updates</h2>
      <UpdatesUpdate item={UPDATES_PROCESSED[0]} big={true} />

      <div className="flex w-full flex-row flex-wrap justify-center [&>*]:my-2.5 [&>*]:mx-[15px]">
        {UPDATES_PROCESSED.slice(1, UPDATES_PROCESSED.length).map((update, index) => (
          <UpdatesUpdate
            key={index}
            item={update}
          />
        ))}
      </div>
    </div>
  );
};
