// src/components/root/rootEco.vue
<template>
  <div class="root-eco root__eco root__container">
    <ModalEco />
    <div class="root__eco__inner root__container__inner">
      <div class="root__eco__left">
        <h2 class="root__eco__title">{{ $t('root.ecoTitle') }}</h2>
        <p class="root__eco__description">
          {{ $t('root.ecoText') }}
        </p>
        <el-button
          class="root__learnMore"
          type="primary"
          @click="$router.push('/eco')"
        >
          {{ $t('root.ecoButton') }}</el-button
        >
      </div>
      <div class="root-eco__right">
        <App
          v-for="app in favs"
          :key="app.id"
          class="root-eco__app"
          :item="app"
          :move="true"
          :show-name="false"
          :open-modal="true"
          app-type="eco"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent, useAsync} from '@nuxtjs/composition-api'
import {shuffleArray} from '../../helpers/util'
import {ECOSYSTEM} from '~/helpers/var'
import {IEcoItem} from '~/types'
export default defineComponent({
  props: {
    full: {
      type: Boolean,
      default: true,
    },
  },

  setup(_props) {
    const favs = useAsync(() => {
      const maxFeatured = 8
      const fixed = ECOSYSTEM.filter((e) => e.featured).slice(0, 1)
      const random = fixed.concat(
        shuffleArray(
          ECOSYSTEM.filter((e) => e.featured).slice(1, ECOSYSTEM.length - 2),
        ).slice(0, maxFeatured - 1),
      )
      return random
    }) as any

    return {
      favs: favs as IEcoItem[],
    }
  },
})
</script>

<style lang="scss">
.root-eco {
  // background: #ebebf5;
  &__inner {
  }

  &__left {
    max-width: 450px;
    width: 100%;
    min-width: 250px;
    margin-right: 25px;
  }

  &__right {
    position: relative;
    height: 250px;
    width: 250px;
    margin-top: 86px;
  }

  &__app {
    position: absolute;
    .app__name {
      font-size: 0.9rem;
    }

    &:nth-of-type(1) {
      top: 0;
      left: 0;
      z-index: 1;
    }
    &:nth-of-type(2) {
      top: -115px;
      left: 35px;
      .app__inner {
        height: 80px;
        width: 80px;
      }
    }
    &:nth-of-type(3) {
      top: -40px;
      left: 150px;
      .app__inner {
        height: 85px;
        width: 85px;
      }
    }
    &:nth-of-type(4) {
      top: 96px;
      left: 151px;

      .app__inner {
        height: 65px;
        width: 65px;
      }
    }
    &:nth-of-type(5) {
      top: -108px;
      left: -86px;
      .app__inner {
        height: 77px;
        width: 77px;
      }
    }
    &:nth-of-type(6) {
      top: 10px;
      left: -102px;
      .app__inner {
        height: 60px;
        width: 60px;
      }
    }
    &:nth-of-type(7) {
      top: 147px;
      left: 13px;
      .app__inner {
        height: 80px;
        width: 80px;
      }
    }
    &:nth-of-type(8) {
      top: 117px;
      left: -93px;
      .app__inner {
        height: 55px;
        width: 55px;
      }
    }
  }
}

@media (max-width: 600px) {
  .root-eco {
    &__right {
      margin-top: 60px;
      margin-bottom: 50px;
      margin-left: 70px;
    }
  }
}
</style>

// apps/web/src/components/root/RootEco.tsx
'use client';

import React, { useMemo } from 'react';
import { useTranslations } from 'next-intl';
import { useRouter } from '@/i18n/routing';
import { Button } from '@/components/ui/button';
import { App } from '@/components/app/App';
import { ModalEco } from '@/components/modal/ModalEco';
import { ECOSYSTEM } from '@/lib/data/var';
import { shuffleArray } from '@/lib/data/util';
import type { IEcoItem } from '@/types';

interface RootEcoProps extends React.HTMLAttributes<HTMLDivElement> {
  full?: boolean;
}

export const RootEco: React.FC<RootEcoProps> = ({ full = true, className, ...props }) => {
  const router = useRouter();
  const t = useTranslations();

  const favs = useMemo(() => {
    const maxFeatured = 8;
    const fixed = ECOSYSTEM.filter((e) => e.featured).slice(0, 1);
    const random = fixed.concat(
      shuffleArray(
        ECOSYSTEM.filter((e) => e.featured).slice(1, ECOSYSTEM.length - 2)
      ).slice(0, maxFeatured - 1)
    );
    return random as IEcoItem[];
  }, []);

  return (
    <div className={`flex flex-1 min-h-[550px] justify-center ${className || ''}`} {...props}>
      <ModalEco />
      <div className="flex flex-row justify-between w-full items-center max-w-[1100px] gap-16 py-20 px-10 max-[900px]:flex-col-reverse max-[900px]:gap-12 max-[700px]:py-[100px]">
        <div className="flex-1 max-w-[500px] max-[900px]:text-center">
          <h2 className="text-4xl font-bold leading-tight mb-6 text-gray-900">{t('root.ecoTitle')}</h2>
          <p className="text-lg text-gray-700 leading-relaxed mb-6">
            {t('root.ecoText')}
          </p>
          <Button
            className="min-w-[160px] text-base py-6 px-8 font-semibold max-[900px]:mx-auto"
            onClick={() => router.push('/eco')}
          >
            {t('root.ecoButton')}
          </Button>
        </div>
        <div className="relative h-[250px] w-[250px] mt-[86px] max-[600px]:mt-[60px] max-[600px]:mb-[50px] max-[600px]:ml-[70px]">
          {favs.map((app, index) => {
            const getSizeForIndex = (idx: number) => {
              const sizes = [110, 80, 85, 65, 80, 55, 60, 77];
              return sizes[idx] || 110;
            };

            return (
              <div
                key={app.id}
                className={`absolute [&_a]:text-[0.9rem] ${index === 0 ? ' z-[1]' :
                  index === 1 ? 'top-[-115px] left-[35px]' :
                    index === 2 ? 'top-[-40px] left-[150px]' :
                      index === 3 ? 'top-[96px] left-[151px]' :
                        index === 4 ? 'top-[147px] left-[13px]' :
                          index === 5 ? 'top-[117px] left-[-93px]' :
                            index === 6 ? 'top-[10px] left-[-102px]' :
                              index === 7 ? 'top-[-108px] left-[-86px]' :
                                ''
                  }`}
              >
                <App
                  item={app}
                  move={true}
                  showName={false}
                  openModal={true}
                  appType="eco"
                  size={getSizeForIndex(index)}
                />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
